tproxy-port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 10809
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - 8.8.8.8
    - 1.1.1.1

proxy-providers:
  Vmess:
    type: file
    path: "./vmess.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Trojan:
    type: file
    path: "./trojan.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Shadowsocks:
    type: file
    path: "./shadowsocks.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  Trojan-go:
    type: file
    path: "./trojan-go.yaml"
    health-check:
       enable: true
       url: http://www.gstatic.com/generate_204
       interval: 300
#Gunakan tanda pagar menghiden, jika salah satu server tidak kepakai
proxy-groups:
- name: VMESS
  type: select
  strategy: consistent-hashing
  use:
    - Vmess 
  url: http://www.gstatic.com/generate_204
  interval: '300'

- name: TROJAN
  type: select
  strategy: consistent-hashing
  use:
    - Trojan
  url: http://www.gstatic.com/generate_204
  interval: '300'

- name: SHADOWSOCKS
  type: select
  strategy: consistent-hashing
  use:
    - Shadowsocks
  url: http://www.gstatic.com/generate_204
  interval: '300'

- name: TROJAN-GO
  type: select
  strategy: consistent-hashing
  use:
    - Trojan-go
  url: http://www.gstatic.com/generate_204
  interval: '300'

- name: BEST-PING
  type: url-test
  strategy: consistent-hashing
  use:
    - Vmess
    - Trojan
    - Shadowsocks
    - Trojan-go
  url: http://www.gstatic.com/generate_204
  interval: '300'

rules:
#- RULE,direct,DIRECT
- MATCH,VMESS
- MATCH,TROJAN
- MATCH,SHADOWSOCKS
- MATCH,TROJAN-GO
- MATCH,BEST-PING
