port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 10809
mode: rule
log-level: silent
external-ui: yacd-gh-pages
allow-lan: true
external-controller: 127.0.0.1:9090
bind-address: "*"
unified-delay: true
ipv6: false
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  follback:
    - https://dns.google/dns-query

proxy-providers:
  Vmess:
    type: file
    path: "./vmess.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
  Trojan:
    type: file
    path: "./trojan.yaml"
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300
      
#Gunakan tanda pagar menghiden, jika salah satu server tidak kepakai
proxy-groups:
- name: SERVER
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
    - Vmess
  #- Trojan 
  url: http://www.gstatic.com/generate_204
  interval: '300'
   
rules:
- MATCH,SERVER
- MATCH,GLOBAL
