#jangan di ganti, kecuali udh benar2 paham
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 10809
mode: rule
log-level: silent
external-ui: yacd-gh-pages
allow-lan: true
external-controller: 127.0.0.1:9090
bind-address: "*"
unified-delay: true
ipv6: false
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  follback:
    - https://dns.google/dns-query  
proxies:
   - {name: XLSGDOV1, server: hynesconstruction.com, port: 80, type: vmess, uuid: 78ec76c5-127a-4939-b9c9-3c6564473e3f, sni: jhzbw6.vpnku.xyz, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: jhzbw6.vpnku.xyz}}}
   - {name: XLAWSV1, server: 104.26.5.10, port: 80, type: vmess, uuid: 2d622252-4d0d-430a-be12-692e7e31a653, sni: 14pw.kalimantan-rev.my.id, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: 14pw.kalimantan-rev.my.id}}}
 
proxy-groups:
  - name: SERVER
    type: select
    proxies: 
    - XLSGDOV1
    - XLAWSV1
  - name: STREAMING  
    type: select
    proxies: 
    - XLSGDOV1
    - XLAWSV1
  - name: SOSIAL MEDIA
    type: select
    proxies:
    - XLSGDOV1
    - XLAWSV1
  - name: SINGAPURE
    type: select
    proxies:
    - XLSGDOV1
    - XLAWSV1
  - name: ADS BLOCK
    type: select
    proxies:
      - SERVER
      - REJECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://bit.ly/3mhQskP"
    path: ./premium/rules/reject.yaml
    interval: 86400    
  sosmed:
    type: http
    behavior: "classical"
    url: "https://bit.ly/3p7R7Y5"
    path: ./premium/rules/sosmed.yaml
    interval: 86400
  streaming:
    behavior: "classical"
    type: http
    url: "https://bit.ly/32f6Iw3"
    #interval: 86400
    path: ./premium/rules/streaming.yaml    
  indonesia:
    behavior: "classical"
    type: http
    url: "https://bit.ly/33HTLvp"
    interval: 86400
    path: ./premium/rules/Indonesian.yaml
rules:
 # - RULE-SET,reject,ADS BLOCK
 # - RULE-SET,indonesia,INDONESIA
 # - RULE-SET,sosmed,SOSIAL MEDIA
 # - RULE-SET,streaming,STREAMING
  - MATCH,SERVER
